version: 2

# Paths to exclude from scanning
paths-ignore:
  - "**/*.md"  # Documentation files
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/build/**"

# Patterns to ignore (environment variable references, not actual secrets)
matches-ignore:
  - name: Environment variable references
    match: (SMTP_PASSWORD|RESEND_API_KEY|SMTP_USER|RESEND_FROM_EMAIL)
